{
 "title": "Drawsiness Detection",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Model Confidence",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT \"confidence\" FROM \"events\""
    }
   ]
  },
  {
   "title": "SOS Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(\"message\")\nFROM \"sos\""
    }
   ]
  },
  {
   "title": "SOS Locations Heatmap",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"latitude\", \"longitude\" FROM \"sos\""
    }
   ]
  },
  {
   "title": "Drivers Events Counts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Count",
     "query": "SELECT COUNT(\"confidence\") AS count \nFROM \"events\" \nGROUP BY \"event_type\""
    }
   ]
  },
  {
   "title": "Users Count Evolution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "users count",
     "query": "SELECT count(\"name\") FROM \"users\" GROUP BY time(1d)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "users",
     "query": "SELECT \"name\", \"email\", \"phone\" FROM \"users\"",
     "select": [
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Events over time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "count",
     "query": "SELECT COUNT(*) FROM \"events\" GROUP BY time(1h)"
    }
   ]
  }
 ]
}